//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanAn
    {
        public int BanAnID { get; set; }
        public string TenBan { get; set; }
        public Nullable<int> SoLuongGhe { get; set; }
        public string ChuY { get; set; }
        public bool TinhTrang { get; set; }
        public string DonGia { get; set; }
        public Nullable<int> KhuVucID { get; set; }
        public Nullable<int> CpyID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> NhanVienID { get; set; }
    }
}
