//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public int BangLuongID { get; set; }
        public int NhanVienID { get; set; }
        public Nullable<int> SoCaChinh { get; set; }
        public Nullable<int> SoCaLe { get; set; }
        public Nullable<int> SoCaNghi { get; set; }
        public Nullable<decimal> LuongCaChinh { get; set; }
        public Nullable<decimal> Thuong { get; set; }
        public Nullable<decimal> ThuongTT { get; set; }
        public Nullable<decimal> TamUng { get; set; }
        public Nullable<decimal> LuongCaLe { get; set; }
        public Nullable<System.DateTime> ThangLinhLuong { get; set; }
        public bool DaNhanLuong { get; set; }
        public Nullable<decimal> SoCaLamThem { get; set; }
        public Nullable<decimal> TienGiuLai { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<decimal> ThucLinh { get; set; }
        public Nullable<System.DateTime> NgayNhanLuong { get; set; }
        public Nullable<int> SoCaLamDu { get; set; }
        public Nullable<int> SoCaLamMuong { get; set; }
        public Nullable<int> SoCaNghiCoLuong { get; set; }
        public Nullable<decimal> TienThuong { get; set; }
        public Nullable<decimal> TienTamUng { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public Nullable<decimal> TongLuongTheoTT { get; set; }
        public Nullable<decimal> TienThucLinh { get; set; }
        public Nullable<decimal> TienPhatDiMuon { get; set; }
        public byte[] LastUpdate { get; set; }
    }
}
