//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class c2_HDCT_HangTL
    {
        public int HoaDonID { get; set; }
        public Nullable<int> mhID { get; set; }
        public string TenMatHang { get; set; }
        public string TenDonViTinh { get; set; }
        public Nullable<decimal> tSoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    }
}
