//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViec
    {
        public int CaID { get; set; }
        public string TenCa { get; set; }
        public Nullable<System.DateTime> TGBatDau { get; set; }
        public Nullable<System.DateTime> TGKetThuc { get; set; }
        public Nullable<bool> DuocSuDung { get; set; }
        public Nullable<decimal> LuongCa { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<int> ThoiGianNghiGiuaGio { get; set; }
        public Nullable<System.DateTime> TGBatDau1 { get; set; }
        public Nullable<System.DateTime> TGKetThuc1 { get; set; }
        public Nullable<int> GroupID { get; set; }
        public byte[] LastUpdate { get; set; }
    }
}
