//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_NguonKhach
    {
        public int NguonKhachID { get; set; }
        public string Ten { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NhanVienPhuTrachID { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
