//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV1
    {
        public int NhomID { get; set; }
        public string MaMH { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> DKTon { get; set; }
        public Nullable<decimal> GiaTri1 { get; set; }
        public Nullable<decimal> Nhap { get; set; }
        public Nullable<decimal> GiaTri2 { get; set; }
        public Nullable<decimal> Xuat { get; set; }
        public Nullable<decimal> GiaTri3 { get; set; }
        public Nullable<decimal> CKTon { get; set; }
        public Nullable<decimal> GiaTri4 { get; set; }
    }
}
