//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachThu
    {
        public int ThuID { get; set; }
        public string Ma { get; set; }
        public string LyDoThu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NhomThuChiID { get; set; }
        public Nullable<int> CpyID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<bool> HienSQTM { get; set; }
        public Nullable<bool> LenBCKQKD { get; set; }
    }
}
