//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatBanMenuChiTiet
    {
        public int DatBanMenuChiTietID { get; set; }
        public int PhieuDatBanID { get; set; }
        public int mhID { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> KhuyenMai { get; set; }
        public Nullable<decimal> SoLuongMien { get; set; }
        public Nullable<decimal> GiaBanDau { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
