//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotKiemKe
    {
        public int DotKiemKeID { get; set; }
        public Nullable<System.DateTime> NgayKiemKe { get; set; }
        public string TenDotKiemKe { get; set; }
        public string KetLuan { get; set; }
        public Nullable<int> KieuKiemKe { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<int> NVID { get; set; }
        public byte[] LastUpdate { get; set; }
    }
}
