//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoCA
    {
        public int ID { get; set; }
        public string NhanVien { get; set; }
        public Nullable<int> TongHDChuaThu { get; set; }
        public Nullable<int> TongHDThuNgan { get; set; }
        public Nullable<int> TongHDNVKhac { get; set; }
        public Nullable<decimal> TienDaThu { get; set; }
        public Nullable<decimal> TienThuHo { get; set; }
        public Nullable<decimal> TienChuaThu { get; set; }
        public Nullable<System.DateTime> NgayGiaoCa { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
