//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangDeTraLai
    {
        public int HangTraLaiID { get; set; }
        public int HoaDonID { get; set; }
        public int mhID { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<bool> DaGiaiQuyet { get; set; }
        public Nullable<int> TruongHopTraLai { get; set; }
        public string FromID { get; set; }
        public Nullable<bool> KhuyenMai { get; set; }
        public Nullable<int> SoLuongDaIn { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
