//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public int HoaDonID { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayLapHoaDon { get; set; }
        public int NhanVienID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<decimal> TienPhaiThu { get; set; }
        public Nullable<decimal> TienKhachTra { get; set; }
        public Nullable<decimal> TienThua { get; set; }
        public Nullable<decimal> TienPhatSinh { get; set; }
        public Nullable<decimal> TienBida { get; set; }
        public Nullable<decimal> MucVAT { get; set; }
        public Nullable<decimal> MucGiamGia { get; set; }
        public Nullable<decimal> MucPhucVu { get; set; }
        public Nullable<decimal> MucChietKhau { get; set; }
        public Nullable<decimal> GiamThua { get; set; }
        public string GhiChu { get; set; }
        public bool ThanhToan { get; set; }
        public bool KhachLe { get; set; }
        public Nullable<int> KieuHoaDon { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<int> SoLuongKhach { get; set; }
        public string TimeService { get; set; }
        public Nullable<int> KhuVucID { get; set; }
        public string TenHoaDon { get; set; }
        public Nullable<int> NguoiDaiDienID { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> SoLanIn { get; set; }
        public int PTTT { get; set; }
        public Nullable<int> KieuTienTe { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<int> TheVIPID { get; set; }
        public Nullable<decimal> GiamGiaMA { get; set; }
        public Nullable<decimal> GiamGiaDU { get; set; }
        public Nullable<int> ThuNganID { get; set; }
        public Nullable<int> BanAnID { get; set; }
        public Nullable<int> NguoiThuTienID { get; set; }
        public Nullable<decimal> GiamGiaKara { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<decimal> GiamGiaTien { get; set; }
        public Nullable<decimal> TienThucDon { get; set; }
        public string MaHoaDonDaIn { get; set; }
        public Nullable<decimal> NgoaiTe { get; set; }
        public Nullable<decimal> TyGia { get; set; }
        public Nullable<bool> BidaPhan { get; set; }
        public string MaGhiTay { get; set; }
    }
}
