//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBanChiTiet
    {
        public int HoaDonBanChiTietID { get; set; }
        public int HoaDonID { get; set; }
        public int mhID { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string Ghichu { get; set; }
        public bool TinhTrang { get; set; }
        public Nullable<bool> KhuyenMai { get; set; }
        public Nullable<decimal> SoLuongMien { get; set; }
        public Nullable<int> MhType { get; set; }
        public Nullable<decimal> TienNguyenLieuPhu { get; set; }
        public Nullable<decimal> GiaBanDau { get; set; }
        public string MaBill { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> SoLuongInBill { get; set; }
        public Nullable<System.DateTime> GioThem { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<decimal> SoLuongLonNhat { get; set; }
        public Nullable<bool> KiemMon { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public Nullable<decimal> SoLuongCon { get; set; }
        public Nullable<System.DateTime> GioLamXong { get; set; }
        public Nullable<int> NotifyID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> NguoiSuaID { get; set; }
        public Nullable<decimal> GiaTam { get; set; }
        public Nullable<int> NotifyClick { get; set; }
        public string NotifyText { get; set; }
        public Nullable<decimal> SLInCheckFood { get; set; }
    }
}
