//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonVAT
    {
        public int ID { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public Nullable<decimal> TienThanhToan { get; set; }
        public string MaVAT { get; set; }
        public Nullable<decimal> TienVAT { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
