//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_TheKho
    {
        public int TheKhoID { get; set; }
        public string MaChungTu { get; set; }
        public Nullable<System.DateTime> NgayLapChungTu { get; set; }
        public Nullable<int> MhID { get; set; }
        public string MaMatHang { get; set; }
        public Nullable<decimal> SoLuongNhap { get; set; }
        public Nullable<decimal> SoLuongXuat { get; set; }
        public Nullable<decimal> SoLuongTon { get; set; }
        public Nullable<int> KhoID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
