//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ketquakd_1
    {
        public int HoaDonBanChiTietID { get; set; }
        public Nullable<decimal> ThanhTienMA { get; set; }
        public Nullable<decimal> ThanhTienDoUong { get; set; }
        public int HoaDonID { get; set; }
        public Nullable<System.DateTime> NgayLapHoaDon { get; set; }
    }
}
