//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiemKeKhoChiTiet
    {
        public int KiemKeKhoChiTietID { get; set; }
        public Nullable<int> DotKiemKeID { get; set; }
        public Nullable<int> MhID { get; set; }
        public Nullable<decimal> SLNhap { get; set; }
        public Nullable<decimal> SLXuat { get; set; }
        public Nullable<decimal> SLTon { get; set; }
        public Nullable<decimal> SLKiem { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> GiaTriThucTe { get; set; }
        public Nullable<decimal> XuatThucTe { get; set; }
        public Nullable<decimal> TonVon { get; set; }
        public Nullable<decimal> TonDauKy { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<decimal> SoLuongPhu1 { get; set; }
        public Nullable<decimal> SoLuongPhu2 { get; set; }
    }
}
