//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class kqkd_2
    {
        public Nullable<decimal> TongTienMA { get; set; }
        public Nullable<decimal> TongTienDouong { get; set; }
        public int HoaDonID { get; set; }
        public decimal MucVAT { get; set; }
        public Nullable<decimal> TienGiamGiaMA { get; set; }
        public Nullable<decimal> TienGiamGiaDoUong { get; set; }
        public Nullable<decimal> GiamGiaMA { get; set; }
        public Nullable<decimal> GiamGiaDU { get; set; }
        public Nullable<decimal> TienBida { get; set; }
        public Nullable<decimal> TienGiamGiaKara { get; set; }
        public Nullable<decimal> GiamGiaKara { get; set; }
        public Nullable<decimal> MucGiamGia { get; set; }
        public Nullable<decimal> TienPhatSinh { get; set; }
        public Nullable<decimal> GiamThua { get; set; }
        public Nullable<decimal> MucPhucVu { get; set; }
    }
}
