//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class kqkd_3
    {
        public int HoaDonID { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<decimal> TienPhucVu { get; set; }
        public Nullable<decimal> TienGiamGiaCuoiCung { get; set; }
        public Nullable<decimal> TienVAT { get; set; }
        public Nullable<decimal> GiamThua { get; set; }
    }
}
