//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiTheVIP
    {
        public int LoaiTheID { get; set; }
        public string TenThe { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<decimal> GiamGiaDA { get; set; }
        public Nullable<decimal> GiamGiaDU { get; set; }
        public Nullable<decimal> GiamGiaTien { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
