//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int LogID { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string NoiDung { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> KhuvucID { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public Nullable<int> BanAnID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
