//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        public int MhID { get; set; }
        public string MaMatHang { get; set; }
        public int NhomID { get; set; }
        public string TenMatHang { get; set; }
        public Nullable<int> DonViTinh { get; set; }
        public string ChuY { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> GiaMua { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<bool> ConHang { get; set; }
        public string MaVach { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public string MoTa { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> SoLuongDauKi { get; set; }
        public byte[] Icon { get; set; }
        public Nullable<int> KieuTienTe { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<decimal> NgoaiTe { get; set; }
        public Nullable<decimal> SoLuongTonToiThieu { get; set; }
        public Nullable<int> PhanTramNL { get; set; }
        public Nullable<decimal> SoLuongTonToiDa { get; set; }
        public Nullable<int> ChietKhau { get; set; }
        public Nullable<int> KTTruocHanSD { get; set; }
        public Nullable<int> NCCID { get; set; }
        public Nullable<int> ChungLoai { get; set; }
        public Nullable<int> MauSac { get; set; }
        public Nullable<int> NuocSX { get; set; }
        public Nullable<int> HangSX { get; set; }
        public Nullable<int> ChatLieu { get; set; }
        public Nullable<decimal> GiaChoThue { get; set; }
        public Nullable<int> KhoID { get; set; }
        public Nullable<int> ThoiGianSuDung { get; set; }
        public string GiaKhac { get; set; }
        public string TenKhac { get; set; }
        public Nullable<bool> IsNguyenLieuDuBi { get; set; }
        public Nullable<decimal> GiaNhapTB { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<bool> DaBan { get; set; }
        public Nullable<int> DonViPhu1 { get; set; }
        public Nullable<decimal> TyLeQuyDoi1 { get; set; }
        public Nullable<int> DonViPhu2 { get; set; }
        public Nullable<decimal> TyLeQuyDoi2 { get; set; }
        public string GiaTheoKhuVuc { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ThoiGianDoiToiDa { get; set; }
    }
}
