//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int NhanVienID { get; set; }
        public int CaLVID { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<int> CpyID { get; set; }
        public string TenNguoiDung { get; set; }
        public string MatKhau { get; set; }
        public string MaNhanVien { get; set; }
        public string Ho { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<decimal> LuongCoBan { get; set; }
        public bool DangThuViec { get; set; }
        public Nullable<System.DateTime> NgayHetHanHopDong { get; set; }
        public string GhiChu { get; set; }
        public string CMTND { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> NgayCong { get; set; }
        public Nullable<System.DateTime> NgayBatDauLam { get; set; }
        public string Quyen { get; set; }
        public Nullable<bool> NVPhucVu { get; set; }
        public Nullable<bool> TinhLuongTheoThang { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<bool> DaNghiViec { get; set; }
        public string TaiKhoanNH { get; set; }
        public Nullable<int> NganHangID { get; set; }
        public string LoginID { get; set; }
    }
}
