//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhap_Hang
    {
        public int mhID { get; set; }
        public string MaMatHang { get; set; }
        public string TenMatHang { get; set; }
        public Nullable<int> SL_Nhap { get; set; }
    }
}
