//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhaChe
    {
        public int PhaCheID { get; set; }
        public int MonAnID { get; set; }
        public Nullable<int> NguyenLieuID { get; set; }
        public Nullable<decimal> SoLuongNguyenLieu { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<decimal> TienNguyenLieu { get; set; }
    }
}
