//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChuyenKho
    {
        public int PhieuChuyenKhoID { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> KhoNhapID { get; set; }
        public Nullable<int> KhoXuatID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public string FromID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
