//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.PhieuNhapChiTiets = new HashSet<PhieuNhapChiTiet>();
        }
    
        public int PhieuNhapID { get; set; }
        public string MaPhieuNhap { get; set; }
        public int NhaCungCapID { get; set; }
        public int NguoiDungID { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public Nullable<decimal> TongGiaTri { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string ChuY { get; set; }
        public bool CongNo { get; set; }
        public string NguoiGiaoHang { get; set; }
        public string FromID { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public Nullable<int> KhoID { get; set; }
        public int KieuNhap { get; set; }
        public Nullable<decimal> TienDaTra { get; set; }
        public Nullable<int> KhoChuyenID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<decimal> TienThanhToan { get; set; }
    
        public virtual ICollection<PhieuNhapChiTiet> PhieuNhapChiTiets { get; set; }
    }
}
