//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatBan
    {
        public int PhieuDatID { get; set; }
        public string MaPhieuDat { get; set; }
        public int KhachHangID { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayTiec { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<decimal> TienDatCoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoBanDat { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public bool DaDen { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<int> KhuVucID { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> SoLuongMam { get; set; }
        public string BanAn { get; set; }
        public Nullable<int> NguoiLapPhieuID { get; set; }
        public Nullable<System.DateTime> ThoiHanDatCocTA { get; set; }
        public Nullable<System.DateTime> ThoiHanDatCocLan2 { get; set; }
        public Nullable<decimal> TienCocThucAn { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> MucDoUuTien { get; set; }
        public Nullable<int> SoBanDuBi { get; set; }
        public byte[] LastUpdate { get; set; }
    }
}
