//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public int PhieuThuID { get; set; }
        public Nullable<int> PhieuThuChiID { get; set; }
        public string MaPhieuThu { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> ThuID { get; set; }
        public string NguoiTra { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<decimal> TongSoTien { get; set; }
        public Nullable<decimal> TienThu { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> NhaCC { get; set; }
        public string FromID { get; set; }
        public Nullable<int> TaiKhoanCoID { get; set; }
        public Nullable<int> CpyID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<bool> ThuCongNo { get; set; }
        public Nullable<bool> HienSQTM { get; set; }
        public Nullable<bool> KhongLenKQKD { get; set; }
        public string ParentID { get; set; }
        public Nullable<bool> HachToanChiPhi { get; set; }
        public Nullable<int> TienTeID { get; set; }
        public Nullable<decimal> NgoaiTe { get; set; }
    }
}
