//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongThucThanhToan
    {
        public int PhuongThucID { get; set; }
        public string TenPT { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> MucPhi { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<int> NganHangID { get; set; }
    }
}
