//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhaHangEntities : DbContext
    {
        public QuanLyNhaHangEntities()
            : base("name=QuanLyNhaHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BanAn> BanAns { get; set; }
        public DbSet<BanAnChiTiet> BanAnChiTiets { get; set; }
        public DbSet<BangLuong> BangLuongs { get; set; }
        public DbSet<CaLamViec> CaLamViecs { get; set; }
        public DbSet<ChamCong> ChamCongs { get; set; }
        public DbSet<ChiTietKhoMatHang> ChiTietKhoMatHangs { get; set; }
        public DbSet<ChungTu> ChungTus { get; set; }
        public DbSet<CRM_NguonKhach> CRM_NguonKhach { get; set; }
        public DbSet<DanhSachChi> DanhSachChis { get; set; }
        public DbSet<DanhSachThu> DanhSachThus { get; set; }
        public DbSet<DatBanMenuChiTiet> DatBanMenuChiTiets { get; set; }
        public DbSet<DoiTac> DoiTacs { get; set; }
        public DbSet<DonViTinh> DonViTinhs { get; set; }
        public DbSet<DotKiemKe> DotKiemKes { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<GiaoCA> GiaoCAs { get; set; }
        public DbSet<HangDeKhuyenMai> HangDeKhuyenMais { get; set; }
        public DbSet<HangDeTraLai> HangDeTraLais { get; set; }
        public DbSet<HoaDonBan> HoaDonBans { get; set; }
        public DbSet<HoaDonBanChiTiet> HoaDonBanChiTiets { get; set; }
        public DbSet<HoaDonVAT> HoaDonVATs { get; set; }
        public DbSet<HoaHong> HoaHongs { get; set; }
        public DbSet<K_TheKho> K_TheKho { get; set; }
        public DbSet<Kho> Khoes { get; set; }
        public DbSet<KhoKhuVuc> KhoKhuVucs { get; set; }
        public DbSet<KhuVucBan> KhuVucBans { get; set; }
        public DbSet<KhuyenMai> KhuyenMais { get; set; }
        public DbSet<KiemKeKhoChiTiet> KiemKeKhoChiTiets { get; set; }
        public DbSet<KieuDoiTac> KieuDoiTacs { get; set; }
        public DbSet<LoaiNhomMatHang> LoaiNhomMatHangs { get; set; }
        public DbSet<LoaiNhomMatHangChiTiet> LoaiNhomMatHangChiTiets { get; set; }
        public DbSet<LoaiTaiSan> LoaiTaiSans { get; set; }
        public DbSet<LoaiTheVIP> LoaiTheVIPs { get; set; }
        public DbSet<LOG> LOGs { get; set; }
        public DbSet<MatHang> MatHangs { get; set; }
        public DbSet<NguoiDaiDien> NguoiDaiDiens { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<NhomCa> NhomCas { get; set; }
        public DbSet<NhomMatHang> NhomMatHangs { get; set; }
        public DbSet<NhomThuChi> NhomThuChis { get; set; }
        public DbSet<PhaChe> PhaChes { get; set; }
        public DbSet<PhieuChi> PhieuChis { get; set; }
        public DbSet<PhieuChuyenKho> PhieuChuyenKhoes { get; set; }
        public DbSet<PhieuDatBan> PhieuDatBans { get; set; }
        public DbSet<PhieuDatBanChiTiet> PhieuDatBanChiTiets { get; set; }
        public DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public DbSet<PhieuNhapChiTiet> PhieuNhapChiTiets { get; set; }
        public DbSet<PhieuThu> PhieuThus { get; set; }
        public DbSet<PhieuXuat> PhieuXuats { get; set; }
        public DbSet<PhieuXuatChiTiet> PhieuXuatChiTiets { get; set; }
        public DbSet<PhongBan> PhongBans { get; set; }
        public DbSet<PhuCapLuong> PhuCapLuongs { get; set; }
        public DbSet<PhuongThucThanhToan> PhuongThucThanhToans { get; set; }
        public DbSet<QuiDoiDonViTinh> QuiDoiDonViTinhs { get; set; }
        public DbSet<Quyen> Quyens { get; set; }
        public DbSet<SRM_DichVuKhachHang> SRM_DichVuKhachHang { get; set; }
        public DbSet<SRM_GiamTaiSan> SRM_GiamTaiSan { get; set; }
        public DbSet<SRM_GiaNhaCC> SRM_GiaNhaCC { get; set; }
        public DbSet<SRM_HoaDonBanChiTietLog> SRM_HoaDonBanChiTietLog { get; set; }
        public DbSet<SRM_KhachTraNoHoaDon> SRM_KhachTraNoHoaDon { get; set; }
        public DbSet<SRM_KhauHaoTaiSan> SRM_KhauHaoTaiSan { get; set; }
        public DbSet<SRM_KhauHaoTaiSanChiTiet> SRM_KhauHaoTaiSanChiTiet { get; set; }
        public DbSet<SRM_KhuyenMaiHoaDon> SRM_KhuyenMaiHoaDon { get; set; }
        public DbSet<SRM_NhomTaiSan> SRM_NhomTaiSan { get; set; }
        public DbSet<SRM_PhieuThuChi> SRM_PhieuThuChi { get; set; }
        public DbSet<SRM_TaiSan> SRM_TaiSan { get; set; }
        public DbSet<SRM_TangTaiSan> SRM_TangTaiSan { get; set; }
        public DbSet<SRM_TinhTrangDoiTac> SRM_TinhTrangDoiTac { get; set; }
        public DbSet<SRM_TinhTrangHangHoa> SRM_TinhTrangHangHoa { get; set; }
        public DbSet<TheKho> TheKhoes { get; set; }
        public DbSet<TheVIP> TheVIPs { get; set; }
        public DbSet<TheVIPChiTiet> TheVIPChiTiets { get; set; }
        public DbSet<ThongTinNH> ThongTinNHs { get; set; }
        public DbSet<TienTe> TienTes { get; set; }
        public DbSet<BanAn_PhieuDB> BanAn_PhieuDB { get; set; }
        public DbSet<BANAN_PHIEUDB_> BANAN_PHIEUDB_ { get; set; }
        public DbSet<c1_28> c1_28 { get; set; }
        public DbSet<c1_HoaDonCT> c1_HoaDonCT { get; set; }
        public DbSet<c2_HangTL_notIn> c2_HangTL_notIn { get; set; }
        public DbSet<c2_HDCT_HangTL> c2_HDCT_HangTL { get; set; }
        public DbSet<cCN1> cCN1 { get; set; }
        public DbSet<cCN2> cCN2 { get; set; }
        public DbSet<cDTKV> cDTKVs { get; set; }
        public DbSet<CV1> CV1 { get; set; }
        public DbSet<ketquakd_1> ketquakd_1 { get; set; }
        public DbSet<kqkd_1Test> kqkd_1Test { get; set; }
        public DbSet<kqkd_2> kqkd_2 { get; set; }
        public DbSet<kqkd_3> kqkd_3 { get; set; }
        public DbSet<kv> kvs { get; set; }
        public DbSet<Nhap_Hang> Nhap_Hangs { get; set; }
        public DbSet<Nhap_TK> Nhap_TK { get; set; }
        public DbSet<tb_ChiTietChi> tb_ChiTietChi { get; set; }
        public DbSet<test_v20> test_v20 { get; set; }
        public DbSet<test_V20_1> test_V20_1 { get; set; }
        public DbSet<thang_v1> thang_v1 { get; set; }
        public DbSet<TongChi_1> TongChi_1 { get; set; }
        public DbSet<TongChi_2> TongChi_2 { get; set; }
        public DbSet<TongGiaTri_PhieuXuat> TongGiaTri_PhieuXuat { get; set; }
        public DbSet<TongHangNhap> TongHangNhaps { get; set; }
        public DbSet<TongHangXuat> TongHangXuats { get; set; }
        public DbSet<View_1> View_1 { get; set; }
        public DbSet<View_2> View_2 { get; set; }
        public DbSet<View_4> View_4 { get; set; }
        public DbSet<View_5> View_5 { get; set; }
        public DbSet<View_6> View_6 { get; set; }
        public DbSet<View_byGD> View_byGD { get; set; }
        public DbSet<view_doanhthutheogd> view_doanhthutheogd { get; set; }
        public DbSet<View_lydoChi> View_lydoChi { get; set; }
        public DbSet<ViewMain> ViewMains { get; set; }
        public DbSet<Xuat_Hang> Xuat_Hangs { get; set; }
        public DbSet<Xuat_TK> Xuat_TK { get; set; }
    }
}
