//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuiDoiDonViTinh
    {
        public int ID { get; set; }
        public Nullable<int> pDonViTinhID { get; set; }
        public Nullable<int> sDonViTinhID { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<decimal> SoLuongQuiDoi { get; set; }
        public Nullable<int> MhID { get; set; }
        public Nullable<bool> IsMacDinh { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
