//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRM_TangTaiSan
    {
        public System.Guid TangTaiSanID { get; set; }
        public string MaTangTaiSan { get; set; }
        public Nullable<System.DateTime> NgayTang { get; set; }
        public Nullable<System.Guid> TaiSanID { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> CongSuat { get; set; }
        public Nullable<int> MucDichID { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> PhongBanID { get; set; }
        public Nullable<decimal> GiaHienTai { get; set; }
        public Nullable<decimal> GiaTriKhauHao { get; set; }
        public Nullable<decimal> GiaTriConLai { get; set; }
        public Nullable<bool> CoGiamGia { get; set; }
        public Nullable<System.DateTime> NgayGiamGia { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> SoThangKhauHao { get; set; }
        public Nullable<decimal> TienKhauHaoMoiThang { get; set; }
        public Nullable<System.DateTime> NgayDuaVaoSuDung { get; set; }
        public Nullable<System.DateTime> NamSanXuat { get; set; }
        public byte[] Data { get; set; }
        public Nullable<System.Guid> FromID { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
