//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRM_KhachTraNoHoaDon
    {
        public int KhachTraNoHoaDonID { get; set; }
        public Nullable<System.DateTime> NgayTraNo { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public Nullable<decimal> SoTienConNo { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
