//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRM_GiaNhaCC
    {
        public int ID { get; set; }
        public Nullable<int> NhaCungCapID { get; set; }
        public Nullable<int> MhID { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string GhiChu { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<System.DateTime> NgayDauGia { get; set; }
        public string TenMatHang { get; set; }
        public string TenNhaCungCap { get; set; }
        public string TenDVT { get; set; }
        public string MaMatHang { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
