//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRM_TaiSan
    {
        public System.Guid TaiSanID { get; set; }
        public string MaTaiSan { get; set; }
        public string TenTaiSan { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> DonViTinhID { get; set; }
        public Nullable<int> DoiTacID { get; set; }
        public Nullable<int> NhomID { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string Tag { get; set; }
        public string Loai { get; set; }
        public byte[] Image { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
