//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRM_GiamTaiSan
    {
        public System.Guid GiamTaiSanID { get; set; }
        public string MaGiamTaiSan { get; set; }
        public Nullable<System.Guid> TangTaiSanID { get; set; }
        public Nullable<System.DateTime> NgayKetThucKhauHao { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayGiam { get; set; }
        public string FromID { get; set; }
        public Nullable<bool> ChoDeBan { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
