//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietChi
    {
        public Nullable<decimal> TongChi { get; set; }
        public int ChiID { get; set; }
        public string LyDoChi { get; set; }
    }
}
