//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class thang_v1
    {
        public int HoaDonID { get; set; }
        public Nullable<decimal> ThanhTienThucDon { get; set; }
        public Nullable<System.DateTime> NgayLapHoaDon { get; set; }
        public Nullable<decimal> TienPhaiThu { get; set; }
        public Nullable<decimal> TienKhachTra { get; set; }
        public Nullable<decimal> TienThua { get; set; }
        public Nullable<decimal> TienPhatSinh { get; set; }
        public Nullable<decimal> TienBida { get; set; }
        public Nullable<decimal> MucVAT { get; set; }
        public Nullable<decimal> MucGiamGia { get; set; }
        public Nullable<decimal> MucPhucVu { get; set; }
        public Nullable<decimal> MucChietKhau { get; set; }
        public Nullable<decimal> GiamThua { get; set; }
        public Nullable<decimal> GiamGiaMA { get; set; }
        public Nullable<decimal> GiamGiaDU { get; set; }
        public Nullable<decimal> GiamGiaKara { get; set; }
    }
}
