//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheVIPChiTiet
    {
        public int TheVIPChiTietID { get; set; }
        public Nullable<int> TheVIPID { get; set; }
        public Nullable<System.DateTime> NgayKhachDen { get; set; }
        public Nullable<int> NVPhucVu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public Nullable<int> DiemCong { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
    }
}
