//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheVIP
    {
        public int TheVIPID { get; set; }
        public string MaThe { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<System.DateTime> NgayTaoThe { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<bool> HetHan { get; set; }
        public Nullable<int> LoaiTheID { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public Nullable<decimal> SoTienNap { get; set; }
        public byte[] LastUpdate { get; set; }
        public Nullable<int> CpyID { get; set; }
        public Nullable<int> KhuyenMaiID { get; set; }
    }
}
