//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNH
    {
        public int ID { get; set; }
        public string TenNH { get; set; }
        public string DienThoai1 { get; set; }
        public string ThuDienTu { get; set; }
        public string DiaChi { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<decimal> TienMatDK { get; set; }
        public Nullable<decimal> TienDeTraLai { get; set; }
        public Nullable<decimal> CongNoThu { get; set; }
        public string Website { get; set; }
        public Nullable<int> TienTe { get; set; }
        public string ActiveCode { get; set; }
        public string Version { get; set; }
        public Nullable<int> CpyID { get; set; }
        public byte[] Data { get; set; }
        public byte[] LastUpdate { get; set; }
    }
}
