//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongChi_1
    {
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public Nullable<int> mhID { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> GiaNhapTB { get; set; }
        public int PhieuXuatID { get; set; }
        public Nullable<int> ChungLoai { get; set; }
    }
}
