//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_4
    {
        public string NgayLap { get; set; }
        public Nullable<int> SK { get; set; }
        public decimal TongTienMat { get; set; }
        public decimal VATTienMat { get; set; }
        public decimal TongTTKhacGhiNo { get; set; }
        public decimal TongTienMatGhiNo { get; set; }
        public decimal TongTTKhac { get; set; }
        public decimal VATTTKhac { get; set; }
        public Nullable<decimal> ThucThuTM { get; set; }
    }
}
