//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public Nullable<decimal> TongThucThu { get; set; }
        public Nullable<decimal> TongPhucVu { get; set; }
        public Nullable<decimal> TongGiamGiaCuoiCung { get; set; }
        public Nullable<decimal> TongVAT { get; set; }
        public Nullable<decimal> TongGiamThua { get; set; }
        public decimal TongChiThucPham { get; set; }
        public decimal TongChiDoUong { get; set; }
        public Nullable<decimal> TongChiNguyenLieuPhu { get; set; }
    }
}
