//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int HoaDonID { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<int> SK { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> PhucVu { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> ThucThu { get; set; }
        public string MaKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public int PTTT { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
