//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMain
    {
        public string NgayLap { get; set; }
        public Nullable<decimal> TongTienMat { get; set; }
        public Nullable<decimal> VATTienMat { get; set; }
        public decimal TongTienTTKhac { get; set; }
        public decimal VATTTKhac { get; set; }
        public Nullable<decimal> Thucthu { get; set; }
        public decimal TienMatGhiNo { get; set; }
        public Nullable<int> SK { get; set; }
    }
}
