//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xuat_TK
    {
        public int mhID { get; set; }
        public string MaMatHang { get; set; }
        public string TenMatHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public string MaPhieuXuat { get; set; }
    }
}
